In [1]:
import numpy as np

In [4]:
# Create an array using NumPy's built in functions. To create an array, we pass a Python list to it.

In [5]:
a = np.array([1, 2, 3])

In [6]:
# Access the elements in the array using indexing

In [7]:
print(a[0])

1


In [8]:
print(a[1])

2


In [9]:
# Create an array full of zeros using the NumPy built-in function

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
# Create an array full of ones using the NumPy built-in function

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
# Add elements to an array

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
# Use the built in np.append() function

In [16]:
np.append(arr, [1,2]) 

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [17]:
# Use the built in np.delete() function to remove elements

In [18]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [19]:
# Sort elements from an array

In [20]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [21]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
# Create a two-dimensional array

In [4]:
import numpy as np

In [6]:
two_dim_array = np.array([(1,2,3), (4,5,6), (7,8,9)])
print(two_dim_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
